import { createFileRoute, Link, useSearch } from '@tanstack/react-router'
import { useQuery } from '@tanstack/react-query'
import { listFiscalDocuments } from '#/modules/fiscal/ui/fiscal-api'

export const Route = createFileRoute('/_app/fiscal/')({ component: FiscalWorkspacePage })

function FiscalWorkspacePage() {
  const { organizationId } = useSearch({ strict: false }) as { organizationId?: string }
  const query = useQuery({ queryKey: ['fiscal-documents', organizationId], queryFn: () => listFiscalDocuments({ data: { organizationId: organizationId ?? '00000000-0000-0000-0000-000000000000' } }), enabled: Boolean(organizationId) })
  return <main className="space-y-6 p-8"><header><p className="text-sm text-muted-foreground">Fiscal</p><h1 className="text-2xl font-semibold">Documentos fiscais internos</h1><p className="text-sm text-muted-foreground">Consulta dos documentos fiscais preparados a partir das operações.</p></header><nav className="flex gap-2 text-sm"><span className="rounded-md border bg-muted px-3 py-2">Documentos</span><Link to="/fiscal" className="rounded-md border px-3 py-2">Origens Fiscais</Link></nav><section className="rounded-lg border p-4"><div className="grid grid-cols-5 gap-4 text-sm font-medium"><span>Número</span><span>Origem</span><span>Cliente</span><span>Status</span><span>Data</span></div>{query.isLoading && <p className="py-8 text-sm text-muted-foreground">Carregando documentos…</p>}{query.isError && <p className="py-8 text-sm text-destructive">Não foi possível carregar os documentos.</p>}{query.data?.ok && query.data.data.map((row: Record<string, unknown>) => <Link key={String(row.fiscal_document_id)} to="/fiscal/documents/$documentId" params={{ documentId: String(row.fiscal_document_id) }} className="grid grid-cols-5 gap-4 border-t py-3 text-sm hover:bg-muted"><span>{String(row.internal_number)}</span><span>{String(row.sales_order_number ?? row.source_document ?? '—')}</span><span>{String(row.customer_name ?? '—')}</span><span>{String(row.status)}</span><span>{String(row.updated_at)}</span></Link>)}{!query.isLoading && query.data?.ok && !query.data.data.length && <p className="py-8 text-sm text-muted-foreground">Nenhum documento fiscal encontrado.</p>}</section></main>
}
