import{createServerFn}from'@tanstack/react-start'
import type{PermissionKey}from'@rescript/permissions'
import type{CreateQuotationInput,CreateSalesOrderInput,ListSalesQuery,SalesDocumentDetail,SalesDocumentType,SalesListItem,UpdateQuotationInput,UpdateSalesOrderInput}from'../domain/types'
export type SalesRpcResult<T>={ok:true;data:T}|{ok:false;error:{code:string;message:string}}
type Client={rpc(n:string,a:Record<string,unknown>):PromiseLike<{data:unknown;error:{message:string}|null}>}
async function context(org:string,permission:PermissionKey){
 const{can,isRolePreset,permissionsForRole}=await import('@rescript/permissions')
 const{createServerSupabaseClient}=await import('#/lib/supabase/server.server')
 const client=createServerSupabaseClient();const{data:{user}}=await client.auth.getUser();if(!user)throw Error('not_authenticated')
 const{data:m}=await client.from('membership').select('role,status').eq('organization_id',org).eq('user_id',user.id).eq('status','active').maybeSingle()
 if(!m||!isRolePreset(m.role)||!can(permissionsForRole(m.role),permission))throw Error('permission_denied')
 return client as unknown as Client
}
async function rpc<T>(c:Client,n:string,a:Record<string,unknown>){const{data,error}=await c.rpc(n,a);if(error)throw Error(error.message);return data as T}
async function run<T>(f:()=>Promise<T>):Promise<SalesRpcResult<T>>{try{return{ok:true,data:await f()}}catch(e){const code=e instanceof Error?e.message:'sales_error';return{ok:false,error:{code,message:code.includes('permission')?'Você não tem permissão para esta operação.':'Não foi possível concluir a operação comercial.'}}}}
const summary=(r:Record<string,unknown>):SalesListItem=>({id:String(r.aggregate_id??r.id),type:r.aggregate_type as SalesDocumentType,number:String(r.number),customerName:String(r.customer_name),customerDocument:r.customer_document==null?null:String(r.customer_document),status:String(r.status),currency:String(r.currency),grandTotal:String(r.grand_total),createdAt:String(r.created_at)})
export const listSalesDocuments=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;type:SalesDocumentType;query:ListSalesQuery})=>d).handler(({data})=>run(async()=>{const rows=await rpc<Record<string,unknown>[]>(await context(data.organizationId,'sales.read'),'list_sales_documents',{p_org:data.organizationId,p_type:data.type,p_query:data.query.q??null,p_status:data.query.status??null,p_limit:data.query.limit??50});return rows.map(summary)}))
export const searchSalesDocuments=listSalesDocuments
export const getSalesDocument=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;type:SalesDocumentType;id:string})=>d).handler(({data})=>run(async()=>{const raw=await rpc<{document:Record<string,unknown>;items:Record<string,unknown>[];history:Record<string,unknown>[]} | null>(await context(data.organizationId,'sales.read'),'get_sales_document',{p_org:data.organizationId,p_type:data.type,p_id:data.id});if(!raw)throw Error('not_found');const d=raw.document,b=summary({...d,aggregate_type:data.type,aggregate_id:d.id});const term=d.payment_term_snapshot as Record<string,unknown>|undefined;return{...b,customerId:String(d.customer_id),customerEmail:d.customer_email==null?null:String(d.customer_email),customerPhone:d.customer_phone==null?null:String(d.customer_phone),subtotal:String(d.subtotal),discountTotal:String(d.discount_total),notes:d.notes==null?null:String(d.notes),validUntil:d.valid_until==null?null:String(d.valid_until),quotationId:d.quotation_id==null?null:String(d.quotation_id),branchId:d.branch_id==null?null:String(d.branch_id),paymentTermId:d.payment_term_id==null?null:String(d.payment_term_id),paymentTermName:term?.name==null?null:String(term.name),confirmedAt:d.confirmed_at==null?null:String(d.confirmed_at),cancelledAt:d.cancelled_at==null?null:String(d.cancelled_at),cancellationReason:d.cancellation_reason==null?null:String(d.cancellation_reason),items:raw.items.map(i=>({id:String(i.id),productId:String(i.product_id),variantId:String(i.variant_id),productName:String(i.product_name),description:i.variant_description==null?null:String(i.variant_description),sku:String(i.sku),unitCode:String(i.unit_code),quantity:String(i.quantity),unitPrice:String(i.unit_price),discount:String(i.discount),subtotal:String(i.subtotal),total:String(i.total),priceListId:i.price_list_id==null?null:String(i.price_list_id),priceSource:i.price_source as'manual'|'price_list',priceRuleSnapshotJson:JSON.stringify(i.price_rule_snapshot??{})})),history:raw.history.map(h=>({id:String(h.id),action:String(h.action),oldValue:h.old_value==null?null:String(h.old_value),newValue:h.new_value==null?null:String(h.new_value),reason:h.reason==null?null:String(h.reason),createdAt:String(h.created_at)}))}satisfies SalesDocumentDetail}))
export const createQuotation=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;input:CreateQuotationInput})=>d).handler(({data})=>run(async()=>{const{validateSalesItems}=await import('../domain/validation');validateSalesItems(data.input.items);return rpc<string>(await context(data.organizationId,'sales.create'),'create_quotation',{p_org:data.organizationId,p_customer:data.input.customerId,p_currency:data.input.currency??'BRL',p_valid_until:data.input.validUntil??null,p_notes:data.input.notes??null,p_items:data.input.items})}))
export const createSalesOrder=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;input:CreateSalesOrderInput})=>d).handler(({data})=>run(async()=>{const{validateSalesItems}=await import('../domain/validation');validateSalesItems(data.input.items);return rpc<string>(await context(data.organizationId,'sales.create'),'create_sales_order_with_context',{p_org:data.organizationId,p_customer:data.input.customerId,p_currency:data.input.currency??'BRL',p_notes:data.input.notes??null,p_items:data.input.items,p_branch:data.input.branchId??null,p_payment_term:data.input.paymentTermId??null,p_quotation:null})}))
export const updateQuotation=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;id:string;input:UpdateQuotationInput})=>d).handler(({data})=>run(async()=>{const{validateSalesItems}=await import('../domain/validation');validateSalesItems(data.input.items);return rpc<string>(await context(data.organizationId,'sales.edit'),'update_quotation',{p_org:data.organizationId,p_id:data.id,p_currency:data.input.currency??'BRL',p_valid_until:data.input.validUntil??null,p_notes:data.input.notes??null,p_items:data.input.items})}))
export const updateSalesOrder=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;id:string;input:UpdateSalesOrderInput})=>d).handler(({data})=>run(async()=>{const{validateSalesItems}=await import('../domain/validation');validateSalesItems(data.input.items);return rpc<string>(await context(data.organizationId,'sales.edit'),'update_sales_order_with_context',{p_org:data.organizationId,p_id:data.id,p_currency:data.input.currency??'BRL',p_notes:data.input.notes??null,p_items:data.input.items,p_branch:data.input.branchId??null,p_payment_term:data.input.paymentTermId??null})}))
export type SalesBranchOption={id:string;name:string;code:string;isDefault:boolean}
export type SalesPaymentTermOption={id:string;name:string;code:string;kind:string;isDefault:boolean}
export const listSalesBranches=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string})=>d).handler(({data})=>run(async()=>{const rows=await rpc<Record<string,unknown>[]>(await context(data.organizationId,'branches.read'),'list_branches',{p_org:data.organizationId,p_status:'active'});return rows.map(row=>({id:String(row.id),name:String(row.name),code:String(row.code),isDefault:Boolean(row.is_default)}))}))
export const listSalesPaymentTerms=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string})=>d).handler(({data})=>run(async()=>{const rows=await rpc<Record<string,unknown>[]>(await context(data.organizationId,'payment_terms.read'),'list_payment_terms',{p_org:data.organizationId,p_status:'active'});return rows.map(row=>({id:String(row.id),name:String(row.name),code:String(row.code),kind:String(row.kind),isDefault:Boolean(row.is_default)}))}))
export const convertQuotationToSalesOrder=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;quotationId:string})=>d).handler(({data})=>run(async()=>rpc<string>(await context(data.organizationId,'sales.convert'),'convert_quotation_to_sales_order',{p_org:data.organizationId,p_quotation:data.quotationId})))
const quotationPermission=(to:string):PermissionKey=>to==='archived'?'sales.archive':to==='approved'?'sales.approve':to==='rejected'||to==='expired'?'sales.reject':to==='sent'?'sales.send':'sales.edit'
export const transitionQuotation=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;id:string;to:string;reason?:string|null})=>d).handler(({data})=>run(async()=>rpc<string>(await context(data.organizationId,quotationPermission(data.to)),'transition_quotation',{p_org:data.organizationId,p_id:data.id,p_to:data.to,p_reason:data.reason??null})))
export const transitionSalesOrder=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;id:string;to:string;reason?:string|null})=>d).handler(({data})=>run(async()=>rpc<string>(await context(data.organizationId,data.to==='archived'?'sales.archive':data.to==='cancelled'?'sales.cancel':'sales.confirm'),'transition_sales_order',{p_org:data.organizationId,p_id:data.id,p_to:data.to,p_reason:data.reason??null})))
