import type { AppCommand } from '#/platform/commands/types'

export const defaultCommands: AppCommand[] = [
  {
    id: 'create.customer',
    label: 'Novo Cliente',
    category: 'create',
    icon: 'customer',
    keywords: ['criar', 'cliente'],
    permission: 'customers.create',
    priority: 90,
    run: ({ navigate }) => navigate('/clientes'),
  },
  {
    id: 'create.product',
    label: 'Novo Produto',
    category: 'create',
    icon: 'product',
    keywords: ['criar', 'produto'],
    permission: 'products.create',
    priority: 85,
    run: ({ navigate }) => navigate('/produtos'),
  },
  {
    id: 'create.sale',
    label: 'Nova Venda',
    category: 'create',
    icon: 'sale',
    keywords: ['criar', 'venda'],
    permission: 'sales.create',
    priority: 95,
    run: ({ navigate }) => navigate('/vendas'),
  },
  {
    id: 'nav.central',
    label: 'Ir para Central',
    category: 'navigate',
    icon: 'central',
    shortcut: 'G H',
    priority: 70,
    run: ({ navigate }) => navigate('/'),
  },
  {
    id: 'nav.customers',
    label: 'Ir para Clientes',
    category: 'navigate',
    icon: 'customer',
    priority: 60,
    run: ({ navigate }) => navigate('/clientes'),
  },
  {
    id: 'nav.products',
    label: 'Ir para Produtos',
    category: 'navigate',
    icon: 'product',
    priority: 60,
    run: ({ navigate }) => navigate('/produtos'),
  },
  {
    id: 'nav.sales',
    label: 'Ir para Vendas',
    category: 'navigate',
    icon: 'sale',
    priority: 60,
    run: ({ navigate }) => navigate('/vendas'),
  },
  {
    id: 'nav.inventory',
    label: 'Ir para Estoque',
    category: 'navigate',
    icon: 'inventory',
    keywords: ['estoque'],
    permission: 'inventory.read',
    priority: 60,
    run: ({ navigate }) => navigate('/estoque'),
  },
  {
    id: 'inventory.entry',
    label: 'Nova Entrada',
    category: 'create',
    icon: 'inventory',
    keywords: ['estoque', 'entrada'],
    permission: 'inventory.move',
    priority: 80,
    run: ({ navigate }) => navigate('/estoque'),
  },
  {
    id: 'inventory.exit',
    label: 'Nova Saída',
    category: 'create',
    icon: 'inventory',
    keywords: ['estoque', 'saida', 'saída'],
    permission: 'inventory.move',
    priority: 79,
    run: ({ navigate }) => navigate('/estoque'),
  },
  {
    id: 'inventory.movements',
    label: 'Ver Movimentações',
    category: 'navigate',
    icon: 'inventory',
    keywords: ['estoque', 'historico', 'histórico', 'movimentacoes'],
    permission: 'inventory.read',
    priority: 55,
    run: ({ navigate }) => navigate('/estoque/movimentacoes'),
  },
  {
    id: 'nav.finance',
    label: 'Ir para Financeiro',
    category: 'navigate',
    icon: 'finance',
    keywords: ['financeiro', 'caixa'],
    permission: 'finance.receive',
    priority: 40,
    run: ({ navigate }) => navigate('/'),
  },
  {
    id: 'search.product',
    label: 'Buscar Produto',
    category: 'search',
    icon: 'search',
    keywords: ['buscar', 'produto'],
    permission: 'products.read',
    priority: 50,
    run: ({ navigate }) => navigate('/produtos'),
  },
  {
    id: 'search.customer',
    label: 'Buscar Cliente',
    category: 'search',
    icon: 'search',
    keywords: ['buscar', 'cliente'],
    permission: 'customers.read',
    priority: 50,
    run: ({ navigate }) => navigate('/clientes'),
  },
]
