import type { AppCommand } from '#/platform/commands/types'

export const defaultCommands: AppCommand[] = [
  {
    id: 'create.customer',
    label: 'Novo Cliente',
    category: 'create',
    icon: 'customer',
    keywords: ['criar', 'cliente'],
    permission: 'customers.create',
    priority: 90,
    run: ({ navigate }) => navigate('/crm/customers/new'),
  },
  {
    id: 'create.product',
    label: 'Novo Produto',
    category: 'create',
    icon: 'product',
    keywords: ['criar', 'produto'],
    permission: 'products.create',
    priority: 85,
    run: ({ navigate }) => navigate('/catalog/products/new'),
  },
  {
    id: 'create.sale',
    label: 'Novo Pedido de Venda',
    category: 'create',
    icon: 'sale',
    keywords: ['criar', 'venda', 'pedido'],
    permission: 'sales.create',
    priority: 95,
    run: ({ navigate }) => navigate('/sales/orders/new'),
  },
  {
    id: 'create.quotation',
    label: 'Novo Orçamento',
    category: 'create',
    icon: 'sale',
    keywords: ['criar', 'orcamento', 'orçamento', 'cotacao', 'cotação'],
    permission: 'sales.create',
    priority: 94,
    run: ({ navigate }) => navigate('/sales/quotations/new'),
  },
  {
    id: 'nav.central',
    label: 'Abrir Centro de Comando',
    category: 'navigate',
    icon: 'central',
    keywords: ['central', 'comando', 'metricas', 'métricas', 'inteligencia', 'inteligência', 'kpis', 'indicadores'],
    permission: 'insights.view',
    shortcut: 'G H',
    priority: 70,
    run: ({ navigate }) => navigate('/app'),
  },
  {
    id: 'nav.analytics',
    label: 'Abrir Métricas',
    category: 'navigate',
    icon: 'trending',
    keywords: ['metricas', 'métricas', 'analytics', 'indicadores', 'kpis', 'relatorios', 'relatórios'],
    permission: 'analytics.view',
    shortcut: 'G M',
    priority: 69,
    run: ({ navigate }) => navigate('/analytics'),
  },
  {
    id: 'nav.customers',
    label: 'Ir para Clientes',
    category: 'navigate',
    icon: 'customer',
    priority: 60,
    run: ({ navigate }) => navigate('/crm/customers'),
  },
  {
    id: 'nav.products',
    label: 'Ir para Produtos',
    category: 'navigate',
    icon: 'product',
    priority: 60,
    run: ({ navigate }) => navigate('/catalog/products'),
  },
  {
    id: 'nav.sales',
    label: 'Ir para Vendas',
    category: 'navigate',
    icon: 'sale',
    priority: 60,
    run: ({ navigate }) => navigate('/sales/orders'),
  },
  {
    id: 'nav.quotations',
    label: 'Ir para Orçamentos',
    category: 'navigate',
    icon: 'sale',
    priority: 59,
    run: ({ navigate }) => navigate('/sales/quotations'),
  },
  {
    id: 'nav.inventory',
    label: 'Ir para Estoque',
    category: 'navigate',
    icon: 'inventory',
    keywords: ['estoque'],
    permission: 'inventory.read',
    priority: 60,
    run: ({ navigate }) => navigate('/catalog/inventory/items'),
  },
  {
    id: 'inventory.entry',
    label: 'Nova Entrada',
    category: 'create',
    icon: 'inventory',
    keywords: ['estoque', 'entrada'],
    permission: 'inventory.move',
    priority: 80,
    run: ({ navigate }) =>
      navigate('/catalog/inventory/movements/new?kind=entry'),
  },
  {
    id: 'inventory.exit',
    label: 'Nova Saída',
    category: 'create',
    icon: 'inventory',
    keywords: ['estoque', 'saida', 'saída'],
    permission: 'inventory.move',
    priority: 79,
    run: ({ navigate }) =>
      navigate('/catalog/inventory/movements/new?kind=exit'),
  },
  {
    id: 'inventory.movements',
    label: 'Ver Movimentações',
    category: 'navigate',
    icon: 'inventory',
    keywords: ['estoque', 'historico', 'histórico', 'movimentacoes'],
    permission: 'inventory.read',
    priority: 55,
    run: ({ navigate }) => navigate('/catalog/inventory/movements'),
  },
  {
    id: 'inventory.reservations',
    label: 'Ver Reservas',
    category: 'navigate',
    icon: 'inventory',
    keywords: ['estoque', 'reserva', 'reservas', 'disponivel', 'disponível'],
    permission: 'reservation.read',
    priority: 56,
    run: ({ navigate }) => navigate('/catalog/inventory/reservations'),
  },
  {
    id: 'inventory.pickings',
    label: 'Ver Separações',
    category: 'navigate',
    icon: 'inventory',
    keywords: ['estoque', 'picking', 'separacao', 'separação'],
    permission: 'picking.read',
    priority: 57,
    run: ({ navigate }) => navigate('/catalog/inventory/pickings'),
  },
  {
    id: 'inventory.packings',
    label: 'Ver Embalagens',
    category: 'navigate',
    icon: 'inventory',
    keywords: ['estoque', 'packing', 'embalagem', 'embalagens'],
    permission: 'packing.read',
    priority: 58,
    run: ({ navigate }) => navigate('/catalog/inventory/packings'),
  },
  {
    id: 'inventory.shipments',
    label: 'Ver Expedições',
    category: 'navigate',
    icon: 'inventory',
    keywords: ['estoque', 'shipment', 'expedicao', 'expedição', 'remessa'],
    permission: 'shipment.read',
    priority: 59,
    run: ({ navigate }) => navigate('/catalog/inventory/shipments'),
  },
  {
    id: 'nav.finance',
    label: 'Ir para Financeiro',
    category: 'navigate',
    icon: 'finance',
    keywords: ['financeiro', 'caixa'],
    permission: 'finance.receive',
    priority: 40,
    run: ({ navigate }) => navigate('/finance/accounts-payable'),
  },
  {
    id: 'create.payment',
    label: 'Registrar Pagamento',
    category: 'create',
    icon: 'finance',
    keywords: ['pagamento', 'baixa', 'financeiro'],
    permission: 'payments.create',
    priority: 88,
    run: ({ navigate }) => navigate('/finance/payments/new?'),
  },
  {
    id: 'nav.payments',
    label: 'Ir para Pagamentos',
    category: 'navigate',
    icon: 'finance',
    permission: 'payments.read',
    priority: 58,
    run: ({ navigate }) => navigate('/finance/payments'),
  },
  {
    id: 'search.product',
    label: 'Buscar Produto',
    category: 'search',
    icon: 'search',
    keywords: ['buscar', 'produto'],
    permission: 'products.read',
    priority: 50,
    run: ({ navigate }) => navigate('/catalog/products'),
  },
  {
    id: 'search.customer',
    label: 'Buscar Cliente',
    category: 'search',
    icon: 'search',
    keywords: ['buscar', 'cliente'],
    permission: 'customers.read',
    priority: 50,
    run: ({ navigate }) => navigate('/crm/customers'),
  },
]
