/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppClientesIndexRouteImport } from './routes/_app/clientes/index'
import { Route as AppClientesCustomerIdRouteImport } from './routes/_app/clientes/$customerId'
import { Route as AppEstoqueIndexRouteImport } from './routes/_app/estoque/index'
import { Route as AppEstoqueMovimentacoesRouteImport } from './routes/_app/estoque/movimentacoes'
import { Route as AppProdutosIndexRouteImport } from './routes/_app/produtos/index'
import { Route as AppProdutosProductIdRouteImport } from './routes/_app/produtos/$productId'
import { Route as AppVendasIndexRouteImport } from './routes/_app/vendas/index'
import { Route as AppVendasSaleIdRouteImport } from './routes/_app/vendas/$saleId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesCustomerIdRoute = AppClientesCustomerIdRouteImport.update({
  id: '/clientes/$customerId',
  path: '/clientes/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueIndexRoute = AppEstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueMovimentacoesRoute = AppEstoqueMovimentacoesRouteImport.update({
  id: '/estoque/movimentacoes',
  path: '/estoque/movimentacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosIndexRoute = AppProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosProductIdRoute = AppProdutosProductIdRouteImport.update({
  id: '/produtos/$productId',
  path: '/produtos/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasIndexRoute = AppVendasIndexRouteImport.update({
  id: '/vendas/',
  path: '/vendas/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasSaleIdRoute = AppVendasSaleIdRouteImport.update({
  id: '/vendas/$saleId',
  path: '/vendas/$saleId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/clientes/$customerId': typeof AppClientesCustomerIdRoute
  '/estoque/movimentacoes': typeof AppEstoqueMovimentacoesRoute
  '/produtos/$productId': typeof AppProdutosProductIdRoute
  '/vendas/$saleId': typeof AppVendasSaleIdRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/estoque/': typeof AppEstoqueIndexRoute
  '/produtos/': typeof AppProdutosIndexRoute
  '/vendas/': typeof AppVendasIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/': typeof AppIndexRoute
  '/clientes/$customerId': typeof AppClientesCustomerIdRoute
  '/estoque/movimentacoes': typeof AppEstoqueMovimentacoesRoute
  '/produtos/$productId': typeof AppProdutosProductIdRoute
  '/vendas/$saleId': typeof AppVendasSaleIdRoute
  '/clientes': typeof AppClientesIndexRoute
  '/estoque': typeof AppEstoqueIndexRoute
  '/produtos': typeof AppProdutosIndexRoute
  '/vendas': typeof AppVendasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clientes/$customerId': typeof AppClientesCustomerIdRoute
  '/_app/estoque/movimentacoes': typeof AppEstoqueMovimentacoesRoute
  '/_app/produtos/$productId': typeof AppProdutosProductIdRoute
  '/_app/vendas/$saleId': typeof AppVendasSaleIdRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/estoque/': typeof AppEstoqueIndexRoute
  '/_app/produtos/': typeof AppProdutosIndexRoute
  '/_app/vendas/': typeof AppVendasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/clientes/$customerId'
    | '/estoque/movimentacoes'
    | '/produtos/$productId'
    | '/vendas/$saleId'
    | '/clientes/'
    | '/estoque/'
    | '/produtos/'
    | '/vendas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/'
    | '/clientes/$customerId'
    | '/estoque/movimentacoes'
    | '/produtos/$productId'
    | '/vendas/$saleId'
    | '/clientes'
    | '/estoque'
    | '/produtos'
    | '/vendas'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/'
    | '/_app/clientes/$customerId'
    | '/_app/estoque/movimentacoes'
    | '/_app/produtos/$productId'
    | '/_app/vendas/$saleId'
    | '/_app/clientes/'
    | '/_app/estoque/'
    | '/_app/produtos/'
    | '/_app/vendas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$customerId': {
      id: '/_app/clientes/$customerId'
      path: '/clientes/$customerId'
      fullPath: '/clientes/$customerId'
      preLoaderRoute: typeof AppClientesCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/': {
      id: '/_app/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AppEstoqueIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/movimentacoes': {
      id: '/_app/estoque/movimentacoes'
      path: '/estoque/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof AppEstoqueMovimentacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos/': {
      id: '/_app/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof AppProdutosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos/$productId': {
      id: '/_app/produtos/$productId'
      path: '/produtos/$productId'
      fullPath: '/produtos/$productId'
      preLoaderRoute: typeof AppProdutosProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas/': {
      id: '/_app/vendas/'
      path: '/vendas'
      fullPath: '/vendas/'
      preLoaderRoute: typeof AppVendasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas/$saleId': {
      id: '/_app/vendas/$saleId'
      path: '/vendas/$saleId'
      fullPath: '/vendas/$saleId'
      preLoaderRoute: typeof AppVendasSaleIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppClientesCustomerIdRoute: typeof AppClientesCustomerIdRoute
  AppEstoqueMovimentacoesRoute: typeof AppEstoqueMovimentacoesRoute
  AppProdutosProductIdRoute: typeof AppProdutosProductIdRoute
  AppVendasSaleIdRoute: typeof AppVendasSaleIdRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppEstoqueIndexRoute: typeof AppEstoqueIndexRoute
  AppProdutosIndexRoute: typeof AppProdutosIndexRoute
  AppVendasIndexRoute: typeof AppVendasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppClientesCustomerIdRoute: AppClientesCustomerIdRoute,
  AppEstoqueMovimentacoesRoute: AppEstoqueMovimentacoesRoute,
  AppProdutosProductIdRoute: AppProdutosProductIdRoute,
  AppVendasSaleIdRoute: AppVendasSaleIdRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppEstoqueIndexRoute: AppEstoqueIndexRoute,
  AppProdutosIndexRoute: AppProdutosIndexRoute,
  AppVendasIndexRoute: AppVendasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
