import { useQuery } from '@tanstack/react-query'
import { useOrganization } from '#/platform/organization/organization-context'
import { getExecutiveDashboard } from '../executive-dashboard-api'

export function ExecutiveDashboardPage() {
  const { currentOrganization } = useOrganization()
  const query = useQuery({ queryKey: ['executive-dashboard', currentOrganization?.id], queryFn: () => getExecutiveDashboard({ data: { organizationId: currentOrganization!.id, period: '30d' } }), enabled: Boolean(currentOrganization?.id) })
  if (query.isLoading) return <main className="p-8 text-sm text-muted-foreground">Carregando dashboard…</main>
  if (query.isError) return <main className="p-8 text-sm text-destructive">Não foi possível carregar o dashboard.</main>
  const data = query.data as { cards: Record<string, number>; revenue: Array<{ date: string; value: number }>; topProducts: Array<{ product: string; quantity: number; value: number }>; finance: Record<string, number>; stock: Record<string, number | null> } | undefined
  if (!data) return <main className="p-8 text-sm text-muted-foreground">Nenhum dado disponível.</main>
  const cards = [['Faturamento hoje', data.cards.revenueToday], ['Faturamento do mês', data.cards.revenueMonth], ['Vendas do mês', data.cards.salesMonth], ['Ticket médio', data.cards.averageTicket], ['Clientes', data.cards.customers], ['Produtos', data.cards.products], ['Contas a receber', data.cards.receivables], ['Contas a pagar', data.cards.payables]]
  return <main className="space-y-6 p-8"><header><p className="text-sm text-muted-foreground">Visão executiva</p><h1 className="text-2xl font-semibold">Dashboard</h1><p className="text-sm text-muted-foreground">A situação comercial, financeira e de estoque da sua empresa.</p></header><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <div key={String(label)} className="rounded-lg border bg-card p-4"><div className="text-sm text-muted-foreground">{label}</div><div className="mt-2 text-2xl font-semibold">{typeof value === 'number' && String(label).includes('Faturamento') || String(label).includes('Ticket') || String(label).includes('Contas') ? `R$ ${Number(value).toLocaleString('pt-BR', { minimumFractionDigits: 2 })}` : Number(value).toLocaleString('pt-BR')}</div></div>)}</section><section className="grid gap-5 lg:grid-cols-2"><div className="rounded-lg border p-4"><h2 className="font-medium">Faturamento por período</h2>{data.revenue.length ? data.revenue.map((row) => <div key={row.date} className="flex justify-between border-t py-2 text-sm"><span>{row.date}</span><span>R$ {Number(row.value).toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</span></div>) : <p className="py-6 text-sm text-muted-foreground">Nenhuma venda confirmada no período.</p>}</div><div className="rounded-lg border p-4"><h2 className="font-medium">Produtos mais vendidos</h2>{data.topProducts.length ? data.topProducts.map((row) => <div key={row.product} className="flex justify-between border-t py-2 text-sm"><span>{row.product}</span><span>{row.quantity} · R$ {Number(row.value).toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</span></div>) : <p className="py-6 text-sm text-muted-foreground">Nenhuma venda confirmada no período.</p>}</div></section><section className="rounded-lg border p-4"><h2 className="font-medium">Estoque</h2><div className="mt-3 flex gap-8 text-sm"><span>Quantidade disponível: <strong>{Number(data.stock.quantity ?? 0).toLocaleString('pt-BR')}</strong></span><span>Valor: não disponível no domínio atual</span></div></section></main>
}
