import{createServerFn}from'@tanstack/react-start';import type{PermissionKey}from'@rescript/permissions';import type{CreateReceivableInput,ListReceivablesQuery,ReceivableDetail,ReceivableListItem}from'../domain/types'
export type RpcResult<T>={ok:true;data:T}|{ok:false;error:{code:string;message:string}};type Client={rpc(n:string,a:Record<string,unknown>):PromiseLike<{data:unknown;error:{message:string}|null}>}
async function ctx(org:string,permission:PermissionKey){
 const{can,isRolePreset,permissionsForRole}=await import('@rescript/permissions')
 const{createServerSupabaseClient}=await import('#/lib/supabase/server.server')
 const c=createServerSupabaseClient()
 const{data:{user}}=await c.auth.getUser()
 if(!user)throw new Error('not_authenticated')
 const{data:m}=await c.from('membership').select('role,status').eq('organization_id',org).eq('user_id',user.id).eq('status','active').maybeSingle()
 if(!m||!isRolePreset(m.role)||!can(permissionsForRole(m.role),permission))throw new Error('permission_denied')
 return c as unknown as Client
}
async function rpc<T>(c:Client,n:string,a:Record<string,unknown>){const{data,error}=await c.rpc(n,a);if(error)throw new Error(error.message);return data as T}async function run<T>(f:()=>Promise<T>):Promise<RpcResult<T>>{try{return{ok:true,data:await f()}}catch(e){const code=e instanceof Error?e.message:'receivable_error';return{ok:false,error:{code,message:code.includes('permission')?'Você não tem permissão para esta operação.':'Não foi possível concluir a operação.'}}}}
const row=(r:Record<string,unknown>):ReceivableListItem=>({id:String(r.accounts_receivable_id??r.id),number:String(r.number),customerId:String(r.customer_id),customerName:String(r.customer_name),customerDocument:r.customer_document==null?null:String(r.customer_document),status:r.status as ReceivableListItem['status'],dueDate:String(r.due_date),totalAmount:String(r.total_amount),openAmount:String(r.open_amount),paidAmount:String(r.paid_amount),currency:String(r.currency)})
export const listReceivables=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;query:ListReceivablesQuery})=>d).handler(({data})=>run(async()=>{const rows=await rpc<Record<string,unknown>[]>(await ctx(data.organizationId,'receivables.read'),'list_receivables',{p_organization_id:data.organizationId,p_query:data.query.q??null,p_status:data.query.status??null,p_due_from:data.query.dueFrom??null,p_due_to:data.query.dueTo??null,p_limit:data.query.limit??50});return rows.map(row)}));export const searchReceivables=listReceivables
export const getReceivable=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;id:string})=>d).handler(({data})=>run(async()=>{const raw=await rpc<{receivable:Record<string,unknown>;installments:Record<string,unknown>[];history:Record<string,unknown>[]} | null>(await ctx(data.organizationId,'receivables.read'),'get_receivable',{p_organization_id:data.organizationId,p_id:data.id});if(!raw)throw new Error('not_found');const b=row(raw.receivable);return{...b,issueDate:String(raw.receivable.issue_date),notes:raw.receivable.notes==null?null:String(raw.receivable.notes),origin:{type:raw.receivable.origin_type as 'manual'|'sales',id:raw.receivable.origin_id==null?null:String(raw.receivable.origin_id)},installments:raw.installments.map(i=>({id:String(i.id),sequence:Number(i.sequence),dueDate:String(i.due_date),originalAmount:String(i.original_amount),openAmount:String(i.open_amount),paidAmount:String(i.paid_amount),status:String(i.status)})),history:raw.history.map(h=>({id:String(h.id),action:String(h.action),reason:h.reason==null?null:String(h.reason),createdAt:String(h.created_at)}))}satisfies ReceivableDetail}))
export const createReceivable=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;input:CreateReceivableInput})=>d).handler(({data})=>run(async()=>{const{validateReceivable}=await import('../domain/validation');validateReceivable(data.input);return rpc<string>(await ctx(data.organizationId,'receivables.create'),'create_receivable',{p_organization_id:data.organizationId,p_customer_id:data.input.customerId,p_issue_date:data.input.issueDate,p_due_date:data.input.dueDate,p_total:data.input.totalAmount,p_currency:data.input.currency,p_notes:data.input.notes??null,p_installments:data.input.installments,p_origin_type:data.input.origin?.type??'manual',p_origin_id:data.input.origin?.id??null})}))
export const updateReceivable=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;id:string;issueDate?:string;dueDate?:string;notes?:string|null})=>d).handler(({data})=>run(async()=>rpc<string>(await ctx(data.organizationId,'receivables.update'),'update_receivable',{p_organization_id:data.organizationId,p_id:data.id,p_issue_date:data.issueDate??null,p_due_date:data.dueDate??null,p_notes:data.notes??null})))
export const openReceivable=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;id:string})=>d).handler(({data})=>run(async()=>rpc<string>(await ctx(data.organizationId,'receivables.update'),'open_receivable',{p_organization_id:data.organizationId,p_id:data.id})))
export const cancelReceivable=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;id:string;reason?:string})=>d).handler(({data})=>run(async()=>rpc<string>(await ctx(data.organizationId,'receivables.cancel'),'cancel_receivable',{p_organization_id:data.organizationId,p_id:data.id,p_reason:data.reason??null})))
export const archiveReceivable=createServerFn({method:'POST'}).inputValidator((d:{organizationId:string;id:string})=>d).handler(({data})=>run(async()=>rpc<string>(await ctx(data.organizationId,'receivables.archive'),'archive_receivable',{p_organization_id:data.organizationId,p_id:data.id})))
