import type { ReactNode } from 'react'
import { MarketingLayout } from './marketing-components'

const cards = [
  ['Vendas conectadas', 'Cada venda concluída atualiza o contexto comercial, o estoque e os indicadores.'],
  ['Estoque por marca', 'Veja peças, variantes, categorias e valor disponível sem abrir vários relatórios.'],
  ['Financeiro claro', 'Contas a receber, contas a pagar e resultado da operação em uma leitura única.'],
  ['Decisões rápidas', 'Compare produtos, vendedores e períodos com números que vêm da operação real.'],
]

function MiniDashboard() {
  return (
    <div className="relative mx-auto max-w-5xl rounded-[1.8rem] border border-white/15 bg-[#111512] p-3 shadow-[0_40px_120px_rgb(0_0_0/0.6)] sm:p-5">
      <div className="flex items-center gap-2 border-b border-white/10 px-2 pb-4"><i className="size-2 rounded-full bg-[#5FE09A]" /><i className="size-2 rounded-full bg-white/20" /><i className="size-2 rounded-full bg-white/20" /><span className="ml-3 h-2 flex-1 rounded-full bg-white/[0.06]" /></div>
      <div className="grid gap-3 p-2 sm:grid-cols-[180px_1fr] sm:p-4">
        <aside className="hidden rounded-2xl border border-white/10 bg-[#0a0d0b] p-4 sm:block"><div className="mb-8 h-3 w-20 rounded bg-[#5FE09A]/60" /><div className="space-y-3 text-xs text-white/45"><b className="block rounded-lg bg-[#5FE09A]/15 p-2 text-[#9af5bb]">Visão geral</b><span className="block p-2">Produtos</span><span className="block p-2">Vendas</span><span className="block p-2">Financeiro</span></div></aside>
        <div className="space-y-3"><div className="grid gap-3 sm:grid-cols-4">{['Faturamento','Vendas','Estoque','Ticket médio'].map((x,i)=><div key={x} className="rounded-xl border border-white/10 bg-white/[0.04] p-3"><p className="text-[10px] text-white/40">{x}</p><strong className="mt-3 block text-lg">{i===1?'128':'R$ 42.800'}</strong><small className="text-[#8beeb2]">+12,4%</small></div>)}</div><div className="grid gap-3 sm:grid-cols-[1.4fr_0.8fr]"><div className="h-48 rounded-xl border border-white/10 bg-[#0a0d0b] p-4"><p className="text-xs text-white/50">Evolução mensal</p><div className="mt-8 flex h-24 items-end gap-2">{[35,60,48,75,55,92,68,100,82,96].map((h,i)=><span key={i} className="flex-1 rounded-t bg-gradient-to-t from-[#246342] to-[#9af5bb]" style={{height:`${h}%`}} />)}</div></div><div className="rounded-xl border border-white/10 bg-[#0a0d0b] p-4"><p className="text-xs text-white/50">Top vendedores</p><div className="mt-5 space-y-3 text-xs">{['Ana Costa','Bruno Lima','Carla Souza'].map((n,i)=><div key={n} className="flex justify-between"><span>{i+1}. {n}</span><b>R$ {18-i*3}.400</b></div>)}</div></div></div></div>
      </div>
    </div>
  )
}

function Section({ eyebrow, title, children, tone = 'dark' }: { eyebrow: string; title: string; children: ReactNode; tone?: 'dark'|'soft' }) {
  return <section className={`px-4 py-28 sm:px-6 lg:px-8 ${tone==='soft'?'bg-[#0b120e]':''}`}><div className="mx-auto max-w-6xl"><p className="text-xs font-semibold tracking-[0.18em] text-[#8beeb2] uppercase">{eyebrow}</p><h2 className="mt-5 max-w-3xl text-4xl leading-[0.96] tracking-[-0.06em] sm:text-6xl">{title}</h2>{children}</div></section>
}

export function RescripetMarketingPage() {
  return <MarketingLayout><main className="overflow-hidden">
    <section className="relative px-4 pb-24 pt-40 text-center sm:px-6 lg:px-8"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_18%,rgb(95_224_154/0.18),transparent_30%),linear-gradient(90deg,transparent_49.8%,rgb(255_255_255/0.035)_50%,transparent_50.2%)]" /><div className="relative mx-auto max-w-6xl"><p className="mx-auto w-fit rounded-full border border-[#5FE09A]/40 bg-[#5FE09A]/10 px-4 py-2 text-xs font-semibold text-[#9af5bb]">PLATAFORMA DE GESTÃO RESCRIPET</p><h1 className="mx-auto mt-8 max-w-5xl text-6xl leading-[0.88] tracking-[-0.08em] sm:text-8xl">Seus números<br />mostram o <span className="text-[#9af5bb]">caminho.</span></h1><p className="mx-auto mt-8 max-w-2xl text-lg leading-8 text-white/55">Controle vendas, estoque, financeiro e desempenho em uma plataforma criada para transformar a operação da sua empresa em decisões claras.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a href="/contact" className="rounded-full bg-[#5FE09A] px-7 py-4 text-sm font-semibold text-[#03110c] shadow-[0_0_50px_rgb(95_224_154/0.28)]">Solicitar demonstração</a><a href="#experiencia" className="rounded-full border border-white/15 px-7 py-4 text-sm font-semibold text-white/80">Conhecer a Rescripet</a></div><div className="mt-20"><MiniDashboard /></div></div></section>
    <Section eyebrow="O que muda" title="Uma empresa inteira na mesma leitura." tone="soft"><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([t,d])=><article key={t} className="min-h-52 rounded-[1.5rem] border border-white/10 bg-[#080b09] p-6"><span className="text-3xl text-[#8beeb2]">＋</span><h3 className="mt-10 text-xl">{t}</h3><p className="mt-3 text-sm leading-6 text-white/50">{d}</p></article>)}</div></Section>
    <Section eyebrow="A operação real" title="Do pedido concluído ao número que orienta a próxima decisão."><div id="experiencia" className="mt-14 grid gap-4 lg:grid-cols-[0.8fr_1.2fr]"><div className="rounded-[1.5rem] border border-white/10 bg-[#080b09] p-8"><p className="text-2xl leading-tight">Venda concluída<br /><span className="text-[#9af5bb]">→ estoque atualizado</span><br /><span className="text-[#9af5bb]">→ financeiro atualizado</span><br /><span className="text-[#9af5bb]">→ indicadores atualizados</span></p><p className="mt-8 text-sm leading-6 text-white/45">Sem etapas artificiais. Os indicadores refletem o que realmente aconteceu na operação.</p></div><MiniDashboard /></div></Section>
    <Section eyebrow="Visão por produto" title="Saiba o que existe, o que gira e onde está o valor." tone="soft"><div className="mt-14 grid gap-4 lg:grid-cols-3"><div className="rounded-[1.5rem] border border-white/10 bg-[#111812] p-7 lg:col-span-2"><div className="flex items-end justify-between"><div><p className="text-sm text-white/45">Estoque por marca</p><strong className="mt-2 block text-4xl">2.540 peças</strong></div><span className="rounded-full bg-[#5FE09A]/15 px-3 py-1 text-xs text-[#9af5bb]">30 dias</span></div><div className="mt-10 space-y-5">{['Marca Aurora','Marca Horizonte','Marca Norte'].map((n,i)=><div key={n}><div className="flex justify-between text-sm"><span>{n}</span><b>{[32,24,18][i]}%</b></div><div className="mt-2 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#5FE09A]" style={{width:`${[82,62,46][i]}%`}} /></div></div>)}</div></div><div className="rounded-[1.5rem] border border-white/10 bg-[#080b09] p-7"><p className="text-sm text-white/45">Capital em estoque</p><strong className="mt-3 block text-4xl">R$ 185 mil</strong><p className="mt-8 text-sm text-[#9af5bb]">12 produtos com estoque baixo</p></div></div></Section>
    <Section eyebrow="Ritmo comercial" title="Veja quem vende, quanto vende e como evolui."><div className="mt-14 overflow-hidden rounded-[1.5rem] border border-white/10 bg-[#080b09]"><div className="grid grid-cols-3 border-b border-white/10 px-6 py-4 text-xs text-white/40"><span>Vendedor</span><span>Vendas</span><span className="text-right">Faturamento</span></div>{['Ana Costa','Bruno Lima','Carla Souza','Diego Alves'].map((n,i)=><div key={n} className="grid grid-cols-3 border-b border-white/[0.06] px-6 py-5 text-sm"><span><b className="mr-3 text-[#8beeb2]">0{i+1}</b>{n}</span><span>{34-i*5} pedidos</span><strong className="text-right">R$ {18-i*3}.400</strong></div>)}</div></Section>
    <section className="px-4 py-32 text-center sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl rounded-[2rem] border border-[#5FE09A]/30 bg-[radial-gradient(circle_at_50%_0%,rgb(95_224_154/0.24),transparent_55%),#101b13] px-6 py-24 shadow-[0_30px_100px_rgb(0_0_0/0.4)]"><p className="text-xs font-semibold tracking-[0.2em] text-[#9af5bb] uppercase">Próximo passo</p><h2 className="mx-auto mt-6 max-w-3xl text-5xl leading-[0.94] tracking-[-0.07em] sm:text-7xl">Enxergue sua empresa com mais clareza.</h2><p className="mx-auto mt-7 max-w-xl text-lg text-white/55">Vendas, estoque, financeiro e indicadores juntos, no ritmo da sua operação.</p><a href="/contact" className="mt-9 inline-flex rounded-full bg-[#5FE09A] px-8 py-4 text-sm font-semibold text-[#03110c]">Solicitar demonstração</a></div></section>
    <section className="px-4 pb-28 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl"><h2 className="text-center text-4xl tracking-[-0.06em] sm:text-6xl">Perguntas frequentes</h2><div className="mt-12 divide-y divide-white/10 rounded-[1.5rem] border border-white/10 bg-[#080b09] px-6">{['Para quais empresas a Rescripet é indicada?','O estoque é atualizado pelas vendas?','Consigo acompanhar produtos e vendedores?','Como funciona a demonstração?'].map(q=><details key={q} className="py-6"><summary className="cursor-pointer list-none text-lg">{q}<span className="float-right text-[#9af5bb]">＋</span></summary><p className="mt-4 max-w-2xl text-sm leading-6 text-white/50">A Rescripet organiza os dados da operação em uma visão clara, respeitando as funcionalidades disponíveis para cada empresa.</p></details>)}</div></div></section>
  </main></MarketingLayout>
}
