import type { ReactNode } from 'react'
import { MarketingLayout } from './marketing-components'

const features = [
  ['Vendas conectadas', 'Cada venda concluida atualiza o contexto comercial, o estoque e os indicadores.'],
  ['Estoque por marca', 'Veja pecas, variantes, categorias e valor disponivel em uma unica leitura.'],
  ['Financeiro claro', 'Contas a receber e a pagar acompanham o ritmo real da operacao.'],
  ['Decisoes rapidas', 'Compare produtos, vendedores e periodos sem planilhas desconectadas.'],
]

function MiniDashboard() {
  return <div className="relative mx-auto max-w-5xl overflow-hidden rounded-[1.8rem] border border-white/15 bg-[#101612] p-3 shadow-[0_40px_120px_rgb(0_0_0/0.65)] sm:p-5">
    <div className="flex items-center gap-2 border-b border-white/10 px-2 pb-4"><i className="size-2 rounded-full bg-[#7df0a9]" /><i className="size-2 rounded-full bg-white/20" /><i className="size-2 rounded-full bg-white/20" /><span className="ml-3 h-2 flex-1 rounded-full bg-white/[0.06]" /></div>
    <div className="grid gap-3 p-2 sm:grid-cols-[180px_1fr] sm:p-4"><aside className="hidden rounded-2xl border border-white/10 bg-[#080c09] p-4 sm:block"><div className="mb-8 h-3 w-20 rounded bg-[#7df0a9]/70" /><div className="space-y-3 text-xs text-white/45"><b className="block rounded-lg bg-[#7df0a9]/15 p-2 text-[#b4f8c8]">Visao geral</b><span className="block p-2">Produtos</span><span className="block p-2">Vendas</span><span className="block p-2">Financeiro</span></div></aside><div className="space-y-3"><div className="grid gap-3 sm:grid-cols-4">{['Faturamento', 'Vendas', 'Estoque', 'Ticket medio'].map((x, i) => <div key={x} className="rounded-xl border border-white/10 bg-white/[0.04] p-3"><p className="text-[10px] text-white/40">{x}</p><strong className="mt-3 block text-lg">{i === 1 ? '128' : 'R$ 42.800'}</strong><small className="text-[#8beeb2]">+12,4%</small></div>)}</div><div className="grid gap-3 sm:grid-cols-[1.4fr_0.8fr]"><div className="h-48 rounded-xl border border-white/10 bg-[#080c09] p-4"><p className="text-xs text-white/50">Evolucao mensal</p><div className="mt-8 flex h-24 items-end gap-2">{[35, 60, 48, 75, 55, 92, 68, 100, 82, 96].map((h, i) => <span key={i} className="flex-1 rounded-t bg-gradient-to-t from-[#246342] to-[#b4f8c8]" style={{ height: `${h}%` }} />)}</div></div><div className="rounded-xl border border-white/10 bg-[#080c09] p-4"><p className="text-xs text-white/50">Top vendedores</p><div className="mt-5 space-y-3 text-xs">{['Ana Costa', 'Bruno Lima', 'Carla Souza'].map((n, i) => <div key={n} className="flex justify-between"><span>{i + 1}. {n}</span><b>R$ {18 - i * 3}.400</b></div>)}</div></div></div></div></div>
  </div>
}

function Section({ eyebrow, title, children, tone = 'dark' }: { eyebrow: string; title: string; children: ReactNode; tone?: 'dark' | 'soft' }) {
  return <section className={`px-4 py-28 sm:px-6 lg:px-8 ${tone === 'soft' ? 'bg-[#0a120d]' : ''}`}><div className="mx-auto max-w-6xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#8beeb2]">{eyebrow}</p><h2 className="mt-5 max-w-4xl text-4xl leading-[0.96] tracking-[-0.06em] sm:text-6xl">{title}</h2>{children}</div></section>
}

function FeatureMosaic() {
  return <div className="mt-14 grid gap-3 md:grid-cols-3"><article className="min-h-72 rounded-[1.6rem] border border-white/10 bg-[radial-gradient(circle_at_20%_0%,rgb(125_240_169/0.2),transparent_55%),#111812] p-7 md:col-span-2"><p className="text-2xl">Operacao conectada.</p><p className="mt-3 max-w-md text-sm leading-6 text-white/50">Do pedido ao caixa, cada etapa preserva o contexto para que sua equipe trabalhe com menos ruido.</p><div className="mt-12 flex items-end gap-2">{[38, 52, 45, 68, 76, 64, 92].map((h, i) => <span key={i} className="flex-1 rounded-t bg-[#7df0a9]/70" style={{ height: `${h}px` }} />)}</div></article><article className="min-h-72 rounded-[1.6rem] border border-white/10 bg-[#111812] p-7"><p className="text-2xl">Uma leitura para decidir.</p><p className="mt-3 text-sm leading-6 text-white/50">Indicadores reais, organizados no momento em que a decisao precisa acontecer.</p><div className="mt-12 rounded-xl border border-[#7df0a9]/25 bg-[#7df0a9]/10 p-4"><span className="text-xs text-[#b4f8c8]">Receita no periodo</span><strong className="mt-2 block text-3xl">R$ 84,2 mil</strong></div></article><article className="min-h-52 rounded-[1.6rem] border border-white/10 bg-[#111812] p-7"><p className="text-xl">Menos planilhas.</p><p className="mt-3 text-sm text-white/50">A operacao permanece em um unico lugar.</p></article><article className="min-h-52 rounded-[1.6rem] border border-white/10 bg-[#0d1510] p-7 md:col-span-2"><p className="text-xl">Mais clareza para o time.</p><div className="mt-8 grid grid-cols-3 gap-3 text-xs text-white/55"><span className="rounded-lg bg-white/[0.04] p-3">Produtos<br /><b className="text-white">412 ativos</b></span><span className="rounded-lg bg-white/[0.04] p-3">Clientes<br /><b className="text-white">1.284 ativos</b></span><span className="rounded-lg bg-white/[0.04] p-3">Pedidos<br /><b className="text-white">128 no mes</b></span></div></article></div>
}

export function RescripetMarketingPage() {
  return <MarketingLayout><main className="overflow-hidden bg-[#050706]">
    <section className="relative px-4 pb-24 pt-40 text-center sm:px-6 lg:px-8"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_12%,rgb(125_240_169/0.16),transparent_30%),linear-gradient(90deg,transparent_49.8%,rgb(255_255_255/0.035)_50%,transparent_50.2%)]" /><div className="relative mx-auto max-w-6xl"><p className="mx-auto w-fit rounded-full border border-[#7df0a9]/35 bg-[#7df0a9]/10 px-4 py-2 text-xs font-semibold text-[#b4f8c8]">PLATAFORMA DE GESTAO RESCRIPET</p><h1 className="mx-auto mt-8 max-w-5xl text-6xl leading-[0.88] tracking-[-0.08em] sm:text-8xl">Seus numeros<br />mostram o <span className="text-[#b4f8c8]">caminho.</span></h1><p className="mx-auto mt-8 max-w-2xl text-lg leading-8 text-white/55">Controle vendas, estoque, financeiro e desempenho em uma plataforma criada para transformar a operacao da sua empresa em decisoes claras.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a href="/contact" className="rounded-full bg-[#7df0a9] px-7 py-4 text-sm font-semibold text-[#03110c] shadow-[0_0_50px_rgb(125_240_169/0.24)]">Solicitar demonstracao</a><a href="#experiencia" className="rounded-full border border-white/15 px-7 py-4 text-sm font-semibold text-white/80">Conhecer a Rescripet</a></div><div className="mt-20"><MiniDashboard /></div></div></section>
    <Section eyebrow="O que muda" title="Uma empresa inteira na mesma leitura." tone="soft"><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{features.map(([t, d]) => <article key={t} className="min-h-52 rounded-[1.5rem] border border-white/10 bg-[#080c09] p-6"><span className="text-3xl text-[#8beeb2]">+</span><h3 className="mt-10 text-xl">{t}</h3><p className="mt-3 text-sm leading-6 text-white/50">{d}</p></article>)}</div></Section>
    <Section eyebrow="A operacao real" title="Do pedido concluido ao numero que orienta a proxima decisao."><div id="experiencia" className="mt-14 grid gap-4 lg:grid-cols-[0.8fr_1.2fr]"><div className="rounded-[1.5rem] border border-white/10 bg-[#080c09] p-8"><p className="text-2xl leading-tight">Venda concluida<br /><span className="text-[#b4f8c8]">→ estoque atualizado</span><br /><span className="text-[#b4f8c8]">→ financeiro atualizado</span><br /><span className="text-[#b4f8c8]">→ indicadores atualizados</span></p><p className="mt-8 text-sm leading-6 text-white/45">Sem etapas artificiais. Os indicadores refletem o que realmente aconteceu na operacao.</p></div><MiniDashboard /></div></Section>
    <Section eyebrow="Recursos que trabalham juntos" title="Tudo o que sua equipe precisa para operar com clareza." tone="soft"><FeatureMosaic /></Section>
    <Section eyebrow="Visao por produto" title="Saiba o que existe, o que gira e onde esta o valor."><div className="mt-14 grid gap-4 lg:grid-cols-3"><div className="rounded-[1.5rem] border border-white/10 bg-[#111812] p-7 lg:col-span-2"><div className="flex items-end justify-between"><div><p className="text-sm text-white/45">Estoque por marca</p><strong className="mt-2 block text-4xl">2.540 pecas</strong></div><span className="rounded-full bg-[#7df0a9]/15 px-3 py-1 text-xs text-[#b4f8c8]">30 dias</span></div><div className="mt-10 space-y-5">{['Marca Aurora', 'Marca Horizonte', 'Marca Norte'].map((n, i) => <div key={n}><div className="flex justify-between text-sm"><span>{n}</span><b>{[32, 24, 18][i]}%</b></div><div className="mt-2 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#7df0a9]" style={{ width: `${[82, 62, 46][i]}%` }} /></div></div>)}</div></div><div className="rounded-[1.5rem] border border-white/10 bg-[#080c09] p-7"><p className="text-sm text-white/45">Capital em estoque</p><strong className="mt-3 block text-4xl">R$ 185 mil</strong><p className="mt-8 text-sm text-[#b4f8c8]">12 produtos com estoque baixo</p></div></div></Section>
    <Section eyebrow="Ritmo comercial" title="Veja quem vende, quanto vende e como evolui." tone="soft"><div className="mt-14 overflow-hidden rounded-[1.5rem] border border-white/10 bg-[#080c09]"><div className="grid grid-cols-3 border-b border-white/10 px-6 py-4 text-xs text-white/40"><span>Vendedor</span><span>Vendas</span><span className="text-right">Faturamento</span></div>{['Ana Costa', 'Bruno Lima', 'Carla Souza', 'Diego Alves'].map((n, i) => <div key={n} className="grid grid-cols-3 border-b border-white/[0.06] px-6 py-5 text-sm"><span><b className="mr-3 text-[#8beeb2]">0{i + 1}</b>{n}</span><span>{34 - i * 5} pedidos</span><strong className="text-right">R$ {18 - i * 3}.400</strong></div>)}</div></Section>
    <Section eyebrow="Como funciona" title="Uma rotina mais simples para o seu time."><div className="mt-14 grid gap-4 lg:grid-cols-2"><div className="rounded-[1.5rem] border border-white/10 bg-[#111812] p-8"><p className="text-5xl tracking-[-0.06em] text-[#b4f8c8]">01—04</p><p className="mt-6 text-2xl">Da primeira venda a uma gestao que aprende com a propria operacao.</p></div><div className="space-y-3">{['Registre a venda com cliente e produtos.', 'Acompanhe estoque, marcas e variantes.', 'Veja o financeiro no mesmo contexto.', 'Decida o proximo movimento com indicadores.'].map((item, i) => <div key={item} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-[#080c09] p-5"><span className="flex size-9 items-center justify-center rounded-full bg-[#7df0a9]/15 text-sm text-[#b4f8c8]">0{i + 1}</span><span className="text-sm text-white/75">{item}</span></div>)}</div></div></Section>
    <section className="px-4 py-32 text-center sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl rounded-[2rem] border border-[#7df0a9]/30 bg-[radial-gradient(circle_at_50%_0%,rgb(125_240_169/0.24),transparent_55%),#101b13] px-6 py-24 shadow-[0_30px_100px_rgb(0_0_0/0.4)]"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#b4f8c8]">Proximo passo</p><h2 className="mx-auto mt-6 max-w-3xl text-5xl leading-[0.94] tracking-[-0.07em] sm:text-7xl">Enxergue sua empresa com mais clareza.</h2><p className="mx-auto mt-7 max-w-xl text-lg text-white/55">Vendas, estoque, financeiro e indicadores juntos, no ritmo da sua operacao.</p><a href="/contact" className="mt-9 inline-flex rounded-full bg-[#7df0a9] px-8 py-4 text-sm font-semibold text-[#03110c]">Solicitar demonstracao</a></div></section>
    <section className="px-4 pb-28 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl"><h2 className="text-center text-4xl tracking-[-0.06em] sm:text-6xl">Perguntas frequentes</h2><div className="mt-12 divide-y divide-white/10 rounded-[1.5rem] border border-white/10 bg-[#080c09] px-6">{['Para quais empresas a Rescripet e indicada?', 'O estoque e atualizado pelas vendas?', 'Consigo acompanhar produtos e vendedores?', 'Como funciona a demonstracao?'].map(q => <details key={q} className="py-6"><summary className="cursor-pointer list-none text-lg">{q}<span className="float-right text-[#b4f8c8]">+</span></summary><p className="mt-4 max-w-2xl text-sm leading-6 text-white/50">A Rescripet organiza os dados da operacao em uma visao clara, respeitando as funcionalidades disponiveis para cada empresa.</p></details>)}</div></div></section>
  </main></MarketingLayout>
}
