import { useMemo,useState } from 'react'
import { useNavigate } from '@tanstack/react-router'
import { AppBreadcrumb } from '#/components/AppBreadcrumb'
import { PageHeader } from '#/components/PageHeader'
import { Button } from '#/components/ui/button'
import { FormField } from '#/components/ui/form-field'
import { Input } from '#/components/ui/input'
import { Select } from '#/components/ui/select'
import { Textarea } from '#/components/ui/textarea'
import { calculateNetAmount,type PaymentMethod } from '#/modules/payments'
import { useConfirmPayment,useCreateFinancialAccount,useCreatePayment,useFinancialAccounts } from '#/modules/payments/ui/use-payments'
import { usePayable,usePayables } from '#/modules/payable/ui/use-payable-queries'
import { RequirePermission,usePermission } from '#/platform/permissions'
import { notificationService } from '#/platform/services'
import { formatBRL,formatDate } from '#/lib/format'

const methods:Record<PaymentMethod,string>={cash:'Dinheiro',bank_transfer:'Transferência bancária',pix_manual:'PIX manual',boleto_manual:'Boleto manual',card_manual:'Cartão manual',other:'Outro'}
const today=()=>new Date().toISOString().slice(0,10)
export function PaymentCreatePage({initialPayableId}:{initialPayableId?:string}){return <RequirePermission permission="payments.create"><Content initialPayableId={initialPayableId}/></RequirePermission>}
function Content({initialPayableId}:{initialPayableId?:string}){
 const navigate=useNavigate();const {can}=usePermission();const payables=usePayables({status:'all',limit:50,sort:'due_asc'});const [payableId,setPayableId]=useState(initialPayableId??'');const payable=usePayable(payableId)
 const accounts=useFinancialAccounts();const createAccount=useCreateFinancialAccount();const create=useCreatePayment();const confirm=useConfirmPayment()
 const [accountId,setAccountId]=useState('');const [method,setMethod]=useState<PaymentMethod>('bank_transfer');const [paidAt,setPaidAt]=useState(today());const [gross,setGross]=useState('0');const [discount,setDiscount]=useState('0');const [interest,setInterest]=useState('0');const [penalty,setPenalty]=useState('0');const [fee,setFee]=useState('0');const [notes,setNotes]=useState('');const [externalReference,setExternalReference]=useState('');const [allocations,setAllocations]=useState<Record<string,string>>({});const [review,setReview]=useState(false);const [error,setError]=useState<string|null>(null);const [accountName,setAccountName]=useState('')
 const options=useMemo(()=>payables.data?.pages.flatMap(p=>p.items).filter(p=>p.status==='approved'||p.status==='partially_paid')??[],[payables.data]);const net=useMemo(()=>{try{return calculateNetAmount({grossAmount:gross,discountAmount:discount,interestAmount:interest,penaltyAmount:penalty,feeAmount:fee})}catch{return null}},[gross,discount,interest,penalty,fee])
 function toggle(id:string,balance:string){setAllocations(current=>{const next={...current};if(id in next)delete next[id];else next[id]=balance;const sum=Object.values(next).reduce((a,v)=>a+Number(v),0);setGross(sum.toFixed(4));return next})}
 async function submit(){setError(null);try{if(!net)throw new Error('Informe um valor líquido válido.');const selected=Object.entries(allocations).map(([installmentId,amount])=>({installmentId,amount}));const paymentId=await create.mutateAsync({financialAccountId:accountId,method,paidAt,grossAmount:gross,discountAmount:discount,interestAmount:interest,penaltyAmount:penalty,feeAmount:fee,allocations:selected,notes,externalReference});await confirm.mutateAsync({paymentId,idempotencyKey:crypto.randomUUID()});notificationService.success('Pagamento confirmado.');await navigate({to:'/finance/payments/$paymentId',params:{paymentId}})}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar o pagamento.')}}
 return <div className="space-y-6"><AppBreadcrumb items={[{label:'Financeiro',href:'/finance/accounts-payable'},{label:'Pagamentos',href:'/finance/payments'},{label:'Registrar'}]}/><PageHeader title="Registrar pagamento" description="Selecione parcelas, informe a origem e revise antes de confirmar."/>
 {error?<p className="rounded-md border border-[var(--color-danger)] p-3 text-sm text-[var(--color-danger)]">{error}</p>:null}
 {!review?<><section className="space-y-4 rounded-md border p-5"><h2 className="font-semibold">1. Parcelas</h2><FormField label="Conta a pagar"><Select value={payableId} onChange={e=>{setPayableId(e.target.value);setAllocations({});setGross('0')}}><option value="">Selecione uma conta</option>{options.map(p=><option key={p.id} value={p.id}>{p.number} · {p.supplierLegalName} · {formatBRL(Number(p.openBalance))}</option>)}</Select></FormField>
 {payable.data?.installments.filter(i=>i.status==='open'||i.status==='partially_paid').map(i=><label key={i.id} className="flex items-center gap-3 rounded-md border p-3"><input type="checkbox" checked={i.id in allocations} onChange={()=>toggle(i.id,i.openBalance)}/><span className="flex-1">Parcela {i.sequence} · vence {formatDate(i.dueDate)} · saldo {formatBRL(Number(i.openBalance))}</span>{i.id in allocations?<Input className="w-36" value={allocations[i.id]} onChange={e=>setAllocations(a=>({...a,[i.id]:e.target.value}))}/>:null}</label>)}</section>
 <section className="grid gap-4 rounded-md border p-5 md:grid-cols-3"><h2 className="md:col-span-3 font-semibold">2. Valores e origem</h2><Money label="Valor bruto" value={gross} set={setGross}/><Money label="Desconto" value={discount} set={setDiscount}/><Money label="Juros" value={interest} set={setInterest}/><Money label="Multa" value={penalty} set={setPenalty}/><Money label="Tarifa" value={fee} set={setFee}/><FormField label="Valor líquido"><Input readOnly value={net??'Inválido'}/></FormField>
 <FormField label="Conta financeira"><Select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Selecione</option>{accounts.data?.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select></FormField><FormField label="Método"><Select value={method} onChange={e=>setMethod(e.target.value as PaymentMethod)}>{Object.entries(methods).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></FormField><FormField label="Data efetiva"><Input type="date" value={paidAt} onChange={e=>setPaidAt(e.target.value)}/></FormField>
 {can('financial_accounts.manage')?<div className="md:col-span-3 flex gap-2"><Input value={accountName} onChange={e=>setAccountName(e.target.value)} placeholder="Nova conta financeira"/><Button variant="secondary" disabled={!accountName.trim()} onClick={()=>void createAccount.mutateAsync({name:accountName,type:'bank'}).then(()=>{setAccountName('');void accounts.refetch()})}>Criar conta bancária</Button></div>:null}
 <FormField label="Referência externa"><Input value={externalReference} onChange={e=>setExternalReference(e.target.value)}/></FormField><FormField label="Observações" className="md:col-span-2"><Textarea value={notes} onChange={e=>setNotes(e.target.value)}/></FormField></section><div className="flex justify-end"><Button disabled={!accountId||!paidAt||!net||Object.keys(allocations).length===0} onClick={()=>setReview(true)}>Revisar pagamento</Button></div></>:<section className="space-y-4 rounded-md border p-5"><h2 className="font-semibold">3. Revisão</h2><p>Fornecedor: <strong>{payable.data?.payable.supplierSnapshot.legalName}</strong></p><p>Parcelas selecionadas: <strong>{Object.keys(allocations).length}</strong></p><p>Valor líquido: <strong>{formatBRL(Number(net))}</strong></p><p>Data efetiva: <strong>{formatDate(paidAt)}</strong></p><div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>setReview(false)}>Voltar</Button><Button disabled={create.isPending||confirm.isPending} onClick={()=>void submit()}>Confirmar pagamento</Button></div></section>}
 </div>
}
function Money({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <FormField label={label}><Input inputMode="decimal" value={value} onChange={e=>set(e.target.value)}/></FormField>}
