-- Internal fiscal document snapshots. No XML or external authorization.

create or replace function public.fiscal_has_permission(p_org uuid,p_permission text) returns boolean language sql stable security definer set search_path=public as $$
select exists(select 1 from public.membership m where m.organization_id=p_org and m.user_id=auth.uid() and m.status='active' and (m.role in('owner','admin') or (m.role='manager' and p_permission like 'fiscal.%') or (m.role='viewer' and p_permission in('fiscal.read','fiscal.preview','fiscal.resolve','fiscal.documents.read')))); $$;

create table public.fiscal_document (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organization(id) on delete restrict,
  internal_number text not null, document_type text not null check(document_type in('sale','purchase','purchase_return','sales_return','transfer')),
  status text not null default 'draft' check(status in('draft','ready','cancelled')), source_document text, source_id uuid, operation_id uuid not null references public.fiscal_operation(id) on delete restrict, tax_profile_id uuid not null references public.tax_profile(id) on delete restrict,
  occurred_at timestamptz not null default now(), responsible_user_id uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid not null references auth.users(id), updated_by uuid not null references auth.users(id), unique(organization_id,internal_number)
);
create table public.fiscal_document_item (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organization(id) on delete restrict, fiscal_document_id uuid not null references public.fiscal_document(id) on delete restrict,
  variant_id uuid not null references public.product_variant(id) on delete restrict, variant_snapshot jsonb not null, quantity numeric(18,4) not null check(quantity>0), unit_code text not null, cfop text, cst text, csosn text, ncm text, origin text, created_at timestamptz not null default now(), created_by uuid not null references auth.users(id), unique(fiscal_document_id,variant_id)
);
create table public.fiscal_document_history (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organization(id) on delete restrict, fiscal_document_id uuid not null references public.fiscal_document(id) on delete restrict, action text not null, actor_user_id uuid not null references auth.users(id), created_at timestamptz not null default now()
);
create table public.fiscal_document_search (
  fiscal_document_id uuid primary key references public.fiscal_document(id) on delete cascade, organization_id uuid not null references public.organization(id) on delete restrict, internal_number text not null, document_type text not null, status text not null, source_document text, operation_id uuid not null, tax_profile_id uuid not null, search_text text not null default '', updated_at timestamptz not null default now()
);
create index fiscal_document_search_text_idx on public.fiscal_document_search using gin(to_tsvector('simple',search_text));
create index fiscal_document_org_status_idx on public.fiscal_document(organization_id,status,occurred_at desc);

create or replace function public.create_fiscal_document(p_org uuid,p_number text,p_type text,p_source_document text,p_source_id uuid,p_operation uuid,p_profile uuid,p_responsible uuid default null) returns public.fiscal_document language plpgsql security definer set search_path=public as $$
declare d public.fiscal_document; begin if not public.fiscal_has_permission(p_org,'fiscal.documents.create') then raise exception 'permission_denied' using errcode='42501'; end if; if not exists(select 1 from fiscal_operation where id=p_operation and organization_id=p_org) or not exists(select 1 from tax_profile where id=p_profile and organization_id=p_org) then raise exception 'cross_tenant_reference'; end if;
insert into fiscal_document(organization_id,internal_number,document_type,source_document,source_id,operation_id,tax_profile_id,responsible_user_id,created_by,updated_by) values(p_org,p_number,lower(p_type),p_source_document,p_source_id,p_operation,p_profile,coalesce(p_responsible,auth.uid()),auth.uid(),auth.uid()) returning * into d;
insert into fiscal_document_history(organization_id,fiscal_document_id,action,actor_user_id) values(p_org,d.id,'FiscalDocumentCreated',auth.uid()); return d; end; $$;

create or replace function public.add_fiscal_document_item(p_org uuid,p_document uuid,p_variant uuid,p_snapshot jsonb,p_quantity numeric,p_unit text,p_cfop text,p_cst text,p_csosn text,p_ncm text,p_origin text) returns public.fiscal_document_item language plpgsql security definer set search_path=public as $$
declare i public.fiscal_document_item; d public.fiscal_document; begin if not public.fiscal_has_permission(p_org,'fiscal.documents.create') then raise exception 'permission_denied'; end if; select * into d from fiscal_document where id=p_document and organization_id=p_org for update; if not found or d.status<>'draft' then raise exception 'fiscal_document_not_editable'; end if; if not exists(select 1 from product_variant where id=p_variant and organization_id=p_org) then raise exception 'cross_tenant_reference'; end if;
insert into fiscal_document_item(organization_id,fiscal_document_id,variant_id,variant_snapshot,quantity,unit_code,cfop,cst,csosn,ncm,origin,created_by) values(p_org,p_document,p_variant,p_snapshot,p_quantity,p_unit,p_cfop,p_cst,p_csosn,p_ncm,p_origin,auth.uid()) returning * into i; return i; end; $$;

create or replace function public.prepare_fiscal_document(p_org uuid,p_document uuid) returns public.fiscal_document language plpgsql security definer set search_path=public as $$
declare d public.fiscal_document; count_items integer; begin if not public.fiscal_has_permission(p_org,'fiscal.documents.create') then raise exception 'permission_denied'; end if; select * into d from fiscal_document where id=p_document and organization_id=p_org for update; if not found or d.status<>'draft' then raise exception 'invalid_transition'; end if; select count(*) into count_items from fiscal_document_item where fiscal_document_id=d.id; if count_items=0 then raise exception 'fiscal_document_without_items'; end if; update fiscal_document set status='ready',updated_at=now(),updated_by=auth.uid() where id=d.id returning * into d; insert into fiscal_document_history(organization_id,fiscal_document_id,action,actor_user_id) values(p_org,d.id,'FiscalDocumentPrepared',auth.uid()); return d; end; $$;
create or replace function public.cancel_fiscal_document(p_org uuid,p_document uuid) returns public.fiscal_document language plpgsql security definer set search_path=public as $$
declare d public.fiscal_document; begin if not public.fiscal_has_permission(p_org,'fiscal.documents.cancel') then raise exception 'permission_denied'; end if; update fiscal_document set status='cancelled',updated_at=now(),updated_by=auth.uid() where id=p_document and organization_id=p_org and status in('draft','ready') returning * into d; if not found then raise exception 'invalid_transition'; end if; insert into fiscal_document_history(organization_id,fiscal_document_id,action,actor_user_id) values(p_org,d.id,'FiscalDocumentCancelled',auth.uid()); return d; end; $$;

create or replace function public.refresh_fiscal_document_search(p_id uuid) returns void language plpgsql security definer set search_path=public as $$
declare d public.fiscal_document%rowtype; terms text; begin select * into d from fiscal_document where id=p_id; if not found then delete from fiscal_document_search where fiscal_document_id=p_id; return; end if; select string_agg(concat_ws(' ',variant_snapshot->>'name',variant_snapshot->>'sku',cfop,cst,ncm),' ') into terms from fiscal_document_item where fiscal_document_id=d.id; insert into fiscal_document_search values(d.id,d.organization_id,d.internal_number,d.document_type,d.status,d.source_document,d.operation_id,d.tax_profile_id,lower(concat_ws(' ',d.internal_number,d.source_document,terms)),now()) on conflict(fiscal_document_id) do update set status=excluded.status,search_text=excluded.search_text,updated_at=now(); end; $$;

alter table public.fiscal_document enable row level security; alter table public.fiscal_document_item enable row level security; alter table public.fiscal_document_history enable row level security; alter table public.fiscal_document_search enable row level security;
create policy fiscal_document_read on fiscal_document for select to authenticated using(fiscal_has_permission(organization_id,'fiscal.documents.read')); create policy fiscal_document_item_read on fiscal_document_item for select to authenticated using(fiscal_has_permission(organization_id,'fiscal.documents.read')); create policy fiscal_document_history_read on fiscal_document_history for select to authenticated using(fiscal_has_permission(organization_id,'fiscal.documents.read')); create policy fiscal_document_search_read on fiscal_document_search for select to authenticated using(fiscal_has_permission(organization_id,'fiscal.documents.read'));
revoke all on fiscal_document,fiscal_document_item,fiscal_document_history,fiscal_document_search from authenticated; grant select on fiscal_document,fiscal_document_item,fiscal_document_history,fiscal_document_search to authenticated;
grant execute on function public.create_fiscal_document(uuid,text,text,text,uuid,uuid,uuid,uuid),public.add_fiscal_document_item(uuid,uuid,uuid,jsonb,numeric,text,text,text,text,text,text),public.prepare_fiscal_document(uuid,uuid),public.cancel_fiscal_document(uuid,uuid) to authenticated;
