-- Explicit fiscal metadata for operational sources; no implicit defaults.

create table public.fiscal_source_metadata (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organization(id) on delete restrict,
  source_type text not null check(source_type in('SALES_ORDER','GOODS_RECEIVING','PURCHASE_RETURN')),
  source_id uuid not null, source_number text not null, fiscal_operation_id uuid not null references public.fiscal_operation(id) on delete restrict, tax_profile_id uuid not null references public.tax_profile(id) on delete restrict,
  origin_state text not null check(origin_state in('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO')),
  destination_state text not null check(destination_state in('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO')),
  fiscal_date date not null, responsible_user_id uuid not null references auth.users(id), status text not null default 'draft' check(status in('draft','valid','archived')), metadata jsonb not null default '{}'::jsonb, version integer not null default 1, supersedes_id uuid references public.fiscal_source_metadata(id), created_at timestamptz not null default now(), created_by uuid not null references auth.users(id), updated_at timestamptz not null default now(), updated_by uuid not null references auth.users(id)
);
create unique index fiscal_source_metadata_active_uidx on public.fiscal_source_metadata(organization_id,source_type,source_id) where status in('draft','valid');
create index fiscal_source_metadata_org_idx on public.fiscal_source_metadata(organization_id,status,source_type);
create table public.fiscal_source_metadata_history (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organization(id) on delete restrict, metadata_id uuid not null references public.fiscal_source_metadata(id) on delete restrict, action text not null, changed_fields jsonb not null default '{}'::jsonb, validation_errors jsonb not null default '[]'::jsonb, actor_user_id uuid not null references auth.users(id), created_at timestamptz not null default now()
);
create table public.fiscal_source_metadata_search (
  metadata_id uuid primary key references public.fiscal_source_metadata(id) on delete cascade, organization_id uuid not null references public.organization(id) on delete restrict, source_type text not null, source_id uuid not null, source_number text not null, fiscal_operation_id uuid not null, tax_profile_id uuid not null, origin_state text not null, destination_state text not null, fiscal_date date not null, responsible_user_id uuid not null, metadata_status text not null, created_at timestamptz not null, updated_at timestamptz not null, search_text text not null default ''
);
create index fiscal_source_metadata_search_text_idx on public.fiscal_source_metadata_search using gin(to_tsvector('simple',search_text));

create or replace function public.fiscal_source_metadata_has_permission(p_org uuid,p_permission text) returns boolean language sql stable security definer set search_path=public as $$ select fiscal_has_permission(p_org,p_permission); $$;
create or replace function public.refresh_fiscal_source_metadata_search(p_id uuid) returns void language plpgsql security definer set search_path=public as $$
declare m public.fiscal_source_metadata%rowtype; op text; prof text; begin select * into m from fiscal_source_metadata where id=p_id; if not found then delete from fiscal_source_metadata_search where metadata_id=p_id; return; end if; select code||' '||name into op from fiscal_operation where id=m.fiscal_operation_id; select code||' '||name into prof from tax_profile where id=m.tax_profile_id; insert into fiscal_source_metadata_search values(m.id,m.organization_id,m.source_type,m.source_id,m.source_number,m.fiscal_operation_id,m.tax_profile_id,m.origin_state,m.destination_state,m.fiscal_date,m.responsible_user_id,m.status,m.created_at,m.updated_at,lower(concat_ws(' ',m.source_number,m.source_type,op,prof,m.origin_state,m.destination_state))) on conflict(metadata_id) do update set metadata_status=excluded.metadata_status,updated_at=excluded.updated_at,search_text=excluded.search_text; end; $$;

create or replace function public.create_fiscal_source_metadata(p_org uuid,p_source_type text,p_source_id uuid,p_operation uuid,p_profile uuid,p_origin text,p_destination text,p_date date,p_responsible uuid,p_metadata jsonb default '{}'::jsonb) returns public.fiscal_source_metadata language plpgsql security definer set search_path=public as $$
declare m public.fiscal_source_metadata; n text; exists_source boolean:=false;
begin if not fiscal_source_metadata_has_permission(p_org,'fiscal.sources.create') then raise exception 'permission_denied' using errcode='42501'; end if; if upper(p_source_type)='INVENTORY_TRANSFER' then raise exception 'FISCAL_SOURCE_NOT_IMPLEMENTED'; end if; if upper(p_source_type) not in('SALES_ORDER','GOODS_RECEIVING','PURCHASE_RETURN') then raise exception 'invalid_source_type'; end if;
select exists(select 1 from sales_order where id=p_source_id and organization_id=p_org) or exists(select 1 from goods_receipt where id=p_source_id and organization_id=p_org) or exists(select 1 from purchase_return where id=p_source_id and organization_id=p_org) into exists_source; if not exists_source then raise exception 'fiscal_source_not_found'; end if;
if not exists(select 1 from fiscal_operation where id=p_operation and organization_id=p_org and status='active') then raise exception 'invalid_fiscal_operation'; end if; if not exists(select 1 from tax_profile where id=p_profile and organization_id=p_org and status='active') then raise exception 'invalid_tax_profile'; end if; if not exists(select 1 from auth.users u join membership mm on mm.user_id=u.id where u.id=p_responsible and mm.organization_id=p_org and mm.status='active') then raise exception 'invalid_responsible'; end if;
select case when upper(p_source_type)='SALES_ORDER' then number when upper(p_source_type)='GOODS_RECEIVING' then number else number end into n from (select number from sales_order where id=p_source_id union all select number from goods_receipt where id=p_source_id union all select number from purchase_return where id=p_source_id) q limit 1; if n is null then raise exception 'fiscal_source_not_found'; end if;
insert into fiscal_source_metadata(organization_id,source_type,source_id,source_number,fiscal_operation_id,tax_profile_id,origin_state,destination_state,fiscal_date,responsible_user_id,metadata,created_by,updated_by) values(p_org,upper(p_source_type),p_source_id,n,p_operation,p_profile,upper(p_origin),upper(p_destination),p_date,p_responsible,p_metadata,auth.uid(),auth.uid()) returning * into m; insert into fiscal_source_metadata_history(organization_id,metadata_id,action,actor_user_id) values(p_org,m.id,'FiscalSourceMetadataCreated',auth.uid()); perform refresh_fiscal_source_metadata_search(m.id); return m; end; $$;

create or replace function public.validate_fiscal_source_metadata(p_org uuid,p_id uuid) returns public.fiscal_source_metadata language plpgsql security definer set search_path=public as $$ declare m public.fiscal_source_metadata; begin if not fiscal_source_metadata_has_permission(p_org,'fiscal.sources.validate') then raise exception 'permission_denied'; end if; select * into m from fiscal_source_metadata where id=p_id and organization_id=p_org for update; if not found or m.status<>'draft' then raise exception 'invalid_transition'; end if; update fiscal_source_metadata set status='valid',updated_at=now(),updated_by=auth.uid() where id=m.id returning * into m; insert into fiscal_source_metadata_history(organization_id,metadata_id,action,actor_user_id) values(p_org,m.id,'FiscalSourceMetadataValidated',auth.uid()); perform refresh_fiscal_source_metadata_search(m.id); return m; end; $$;
create or replace function public.archive_fiscal_source_metadata(p_org uuid,p_id uuid) returns public.fiscal_source_metadata language plpgsql security definer set search_path=public as $$ declare m public.fiscal_source_metadata; begin if not fiscal_source_metadata_has_permission(p_org,'fiscal.sources.archive') then raise exception 'permission_denied'; end if; update fiscal_source_metadata set status='archived',updated_at=now(),updated_by=auth.uid() where id=p_id and organization_id=p_org and status in('draft','valid') returning * into m; if not found then raise exception 'invalid_transition'; end if; insert into fiscal_source_metadata_history(organization_id,metadata_id,action,actor_user_id) values(p_org,m.id,'FiscalSourceMetadataArchived',auth.uid()); perform refresh_fiscal_source_metadata_search(m.id); return m; end; $$;

alter table fiscal_source_metadata enable row level security; alter table fiscal_source_metadata_history enable row level security; alter table fiscal_source_metadata_search enable row level security;
create policy fiscal_source_metadata_read on fiscal_source_metadata for select to authenticated using(fiscal_source_metadata_has_permission(organization_id,'fiscal.sources.read')); create policy fiscal_source_metadata_history_read on fiscal_source_metadata_history for select to authenticated using(fiscal_source_metadata_has_permission(organization_id,'fiscal.sources.read')); create policy fiscal_source_metadata_search_read on fiscal_source_metadata_search for select to authenticated using(fiscal_source_metadata_has_permission(organization_id,'fiscal.sources.read'));
revoke all on fiscal_source_metadata,fiscal_source_metadata_history,fiscal_source_metadata_search from authenticated; grant select on fiscal_source_metadata,fiscal_source_metadata_history,fiscal_source_metadata_search to authenticated;
grant execute on function public.create_fiscal_source_metadata(uuid,text,uuid,uuid,uuid,text,text,date,uuid,jsonb),public.validate_fiscal_source_metadata(uuid,uuid),public.archive_fiscal_source_metadata(uuid,uuid) to authenticated;
